apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: influxdb-app
  name: influxdb-svc
spec:
  selector:
    app: influxdb-app
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb
        image: influxdb_image
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        volumeMounts:
          - name: influxdb-volume
            mountPath: /root/.influxdb
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
