apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: mysql-app
  name: mysql-svc
spec:
  selector:
    app: mysql-app
  type: ClusterIP
  ports:
  - protocol: TCP
    name: mysql
    port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-app
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
      name: mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-volume
            mountPath: "var/lib/mysql"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-app
  name: mysql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi