apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb-svc:8086
    database: telegraf
    # version: 1
    # editable: false
    # basicAuth: true
    # basicAuthUser: root
    # basicAuthPassword: root