apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-app
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin-app
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.99.201
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-app
spec:
  selector:
    matchLabels:
      app: phpmyadmin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
        - name: phpmyadmin
          image: php_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000